eureka:
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uip_sms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: r4HeH71K$s